// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/BarChart.vue')['default']
    ComputedProps: typeof import('./components/ComputedProps.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    FirstChart: typeof import('./components/FirstChart.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HiBarChart: typeof import('./components/HiBarChart.vue')['default']
    HiChart: typeof import('./components/HiChart.vue')['default']
    HiChart2: typeof import('./components/HiChart2.vue')['default']
    VueCheatSheet: typeof import('./components/VueCheatSheet.vue')['default']
  }
}

export {}
